config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :achievement, only: [:new, :create]
  root to: 'welcome#index'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  def new

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/achievement_controller.rb
class AchievementController < ApplicationController
  def new
    @achievement = Achievement.new
  end

  def create

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/achievement_helper.rb
module AchievementHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/achievement/new.html.erb
<%= simple_form_for :achievement do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <-- %= f.input :privacy, collection: Hash[Achievement.privacies.map{|k,v| [k.split('_').first.capitalize, k ]}] % -->
  <%= f.input :featured %>
  <%= f.input :cover_image %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IRock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container-fluid">
    <ul>
      <li><%= link_to 'New Achievement', new_achievement_path %></li>

    </ul>
    <%= yield %>
  </div>

  </body>
</html>

app/views/welcome/index.html.erb
Welcome